In [9]:
#http://dataaspirant.com/2017/02/01/decision-tree-algorithm-python-with-scikit-learn/
#http://stackabuse.com/decision-trees-in-python-with-scikit-learn/
import pandas as pd  
import numpy as np  
import matplotlib.pyplot as plt  
%matplotlib inline

In [14]:
dataset = pd.read_csv("survey_formatado_country_virgula.csv")  

In [15]:
dataset.shape  

(1250, 29)

In [16]:
dataset.head()  

Timestamp    Age_  Age Gender_                 Gender  \
0  27/08/2014 11:43  18|-28   18       M                   Male   
1  27/08/2014 12:15  18|-28   18       M  something kinda male?   
2  27/08/2014 12:31  18|-28   18       M                   Male   
3  27/08/2014 14:10  18|-28   18       M                   male   
4  27/08/2014 14:11  18|-28   18       M                   Male   

      Continent_        Country state self_employed family_history  \
0         Europe    Netherlands   NaN            No             No   
1        Eurasia         Russia   NaN            No             No   
2  North America  United States    CT            No             No   
3  North America  United States    TX            No             No   
4  North America  United States    WA            No             No   

        ...         anonymity               leave mental_health_consequence  \
0       ...        Don t know  Somewhat difficult                       Yes   
1       ...               Yes       Somewhat easy                        No   
2       ...               Yes           Very easy                        No   
3       ...        Don t know          Don t know                       Yes   
4       ...        Don t know           Very easy                        No   

  phys_health_consequence     coworkers    supervisor mental_health_interview  \
0                   Maybe            No  Some of them                      No   
1                      No           Yes           Yes                     Yes   
2                      No  Some of them            No                      No   
3                      No            No            No                      No   
4                      No  Some of them  Some of them                      No   

  phys_health_interview mental_vs_physical obs_consequence  
0                    No                 No              No  
1                   Yes         Don t know              No  
2                    No         Don t know              No  
3                 Maybe         Don t know              No  
4                 Maybe                Yes              No  

[5 rows x 29 columns]

In [39]:
from sklearn import preprocessing

#>>> le.fit([1, 2, 2, 6])
#LabelEncoder()
#>>> le.classes_
#array([1, 2, 6])
#>>> le.transform([1, 1, 2, 6]) 
#array([0, 0, 1, 2]...)
#>>> le.inverse_transform([0, 0, 1, 2])
#array([1, 1, 2, 6])


#le = preprocessing.LabelEncoder()
#le.fit(["No", "Yes", "Maybe"])

#list(le.classes_)
#le.transform(["No", "Yes", "Maybe"]) 

#list(le.inverse_transform([2, 2, 1]))



from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

train = ["No", "Yes", "Maybe"]
test = ["No", "No", "Maybe"]
le.fit(train).transform(test)

dataset.apply(LabelEncoder().fit_transform)

TypeError: ("'<' not supported between instances of 'str' and 'float'", 'occurred at index state')

In [30]:
X = dataset.drop('treatment', axis=1)  
y = dataset['treatment']  

In [31]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)  

In [32]:
X_train

Timestamp     Age_  Age Gender_  Gender     Continent_  \
179   27/08/2014 16:26   18|-28   25       M    male  North America   
651   27/08/2014 12:11   28|-38   32       M       M  North America   
876   27/08/2014 14:14   28|-38   35       M    male  North America   
295   27/08/2014 11:50   18|-28   27       M    Male         Europe   
844   29/08/2014 09:31   28|-38   34       M    male  North America   
34    28/08/2014 10:20   18|-28   21       M    male         Europe   
762   27/08/2014 22:36   28|-38   33       M    Male  North America   
163   27/08/2014 13:33   18|-28   25       M    Male         Africa   
447   27/08/2014 14:28   28|-38   29       M    male         Europe   
92    28/08/2014 09:54   18|-28   23       M    male  North America   
485   28/08/2014 10:30   28|-38   29       M    Male  North America   
71    27/08/2014 13:56   18|-28   23       F  female  North America   
533   27/08/2014 14:31   28|-38   30       M    Male  North America   
69    27/08/2014 13:39   18|-28   23       M    Male  North America   
262   28/08/2014 10:01   18|-28   26       M    Male  North America   
517   27/08/2014 11:44   28|-38   30       M    male  North America   
746   27/08/2014 14:41   28|-38   33       M    Male         Europe   
210   01/09/2014 06:52   18|-28   25       M    Male         Europe   
1135  28/08/2014 17:33   38|-48   42       M    male  North America   
108   24/02/2015 09:13   18|-28   23       M    Male         Europe   
705   29/08/2014 04:53   28|-38   32       M    Male         Europe   
826   27/08/2014 21:15   28|-38   34       M    Male  North America   
1039  27/08/2014 12:37   38|-48   39       M    Male  North America   
976   28/08/2014 10:08   28|-38   37       M    male  North America   
902   28/08/2014 17:27   28|-38   35       M    Male  North America   
588   27/08/2014 12:17   28|-38   31       M    male  South America   
575   04/04/2015 11:22   28|-38   30       M    male         Europe   
502   29/08/2014 11:22   28|-38   29       F       f         Europe   
792   30/08/2014 05:47   28|-38   33       F  female  North America   
376   27/08/2014 13:14   28|-38   28       M    male  North America   
...                ...      ...  ...     ...     ...            ...   
880   27/08/2014 15:25   28|-38   35       M    Male         Europe   
456   27/08/2014 15:25   28|-38   29       M    Male  North America   
991   29/08/2014 16:50   28|-38   37       M    male         Europe   
101   01/09/2014 08:19   18|-28   23       M    Male         Europe   
884   27/08/2014 17:15   28|-38   35       M    Male  North America   
79    27/08/2014 15:46   18|-28   23       M       M  North America   
784   29/08/2014 04:39   28|-38   33       M       M         Europe   
53    28/08/2014 04:02   18|-28   22       F  Female         Europe   
903   28/08/2014 20:12   28|-38   35       M    Male  North America   
942   28/08/2014 16:52   28|-38   36       M    male         Europe   
6     27/08/2014 16:19   18|-28   18       F  Female         Europe   
214   24/02/2015 09:00   18|-28   25       M    Male         Europe   
917   27/08/2014 11:33   28|-38   36       M    Male  North America   
420   31/08/2014 09:19   28|-38   28       M    male  North America   
324   27/08/2014 16:03   18|-28   27       M       M  North America   
1146  27/08/2014 16:18   38|-48   43       M       M  North America   
1106  27/08/2014 13:54   38|-48   41       M    Male  North America   
66    27/08/2014 12:49   18|-28   23       F  Female  North America   
326   27/08/2014 16:23   18|-28   27       M    Male           Asia   
507   30/08/2014 11:48   28|-38   29       M       M         Europe   
382   27/08/2014 14:21   28|-38   28       F  female  North America   
810   27/08/2014 13:29   28|-38   34       M    Male         Europe   
1187  27/08/2014 15:22   38|-48   45       M       M  North America   
1033  16/11/2014 08:42   38|-48   38       M    Male  North America   
298   27/08/2014 12:33   18|-28   27 

In [33]:
from sklearn.tree import DecisionTreeClassifier  
classifier = DecisionTreeClassifier()  
classifier.fit(X_train, y_train)  

ValueError: could not convert string to float: 'No'

In [8]:
import csv
with open('survey_formatado.csv', newline='') as csvfile:
     csv_reader = csv.reader(csvfile)
        
     next(csv_reader)
        
     for row in csv_reader:
         print(row[0])

27/08/2014 11:43
27/08/2014 12:15
27/08/2014 12:31
27/08/2014 14:10
27/08/2014 14:11
27/08/2014 16:16
27/08/2014 16:19
27/08/2014 11:57
27/08/2014 12:34
27/08/2014 12:40
27/08/2014 22:07
28/08/2014 09:02
28/08/2014 11:15
29/08/2014 09:13
29/08/2014 10:05
29/08/2014 10:30
27/08/2014 15:40
28/08/2014 05:05
28/08/2014 15:32
29/08/2014 09:15
30/08/2014 20:46
14/09/2014 09:04
27/08/2014 12:31
27/08/2014 13:03
27/08/2014 13:35
27/08/2014 15:14
27/08/2014 15:15
27/08/2014 15:22
27/08/2014 15:29
27/08/2014 15:34
27/08/2014 17:47
27/08/2014 18:22
27/08/2014 18:56
28/08/2014 09:16
28/08/2014 10:20
28/08/2014 11:34
28/08/2014 16:58
01/09/2014 08:23
27/08/2014 11:44
27/08/2014 12:29
27/08/2014 12:37
27/08/2014 12:49
27/08/2014 13:31
27/08/2014 14:03
27/08/2014 14:27
27/08/2014 14:47
27/08/2014 15:15
27/08/2014 15:28
27/08/2014 16:42
27/08/2014 17:56
27/08/2014 19:13
28/08/2014 01:04
28/08/2014 01:19
28/08/2014 04:02
28/08/2014 06:11
28/08/2014 08:23
28/08/2014 13:11
28/08/2014 19:28
06/05/2015 10:

In [ ]:
from sklearn import tree
Y = csv_reader[][100]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(csv_reader, Y)